import { mkdirSync, writeFileSync, existsSync, readFileSync } from "fs";
import { resolve, dirname, relative, basename } from "path";
import { fileURLToPath } from "url";

// Framework lives at <monorepo>/framework, a sibling of cli/. Resolving from
// this module's own location (cli/src/commands/scaffold.ts) is CWD-independent
// and matches the semantics the e2e tests pass via FRAMEWORK_DIR.
const DEFAULT_FRAMEWORK_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "framework");
import { validateAnalysis } from "./validate.js";
import { generateEnums } from "../generators/enums.js";
import { generateErrors } from "../generators/errors.js";
import { generateRegistry } from "../generators/registry.js";
import { generateContractTests } from "../generators/contract-tests.js";
import { generateMockAdapterTests } from "../generators/mock-adapter-tests.js";
import { generateAdapterTypes, toDtoName, tsType, buildMethodMap, safeFieldName } from "../generators/adapter-types.js";
import { generateMockAdapter } from "../generators/mock-adapter.js";
import { generateToolHandlers } from "../generators/tool-handlers.js";
import { generateYunosAdapterRpc } from "../generators/yunos-adapter-rpc.js";
import { generateRpcBridge } from "../generators/rpc-bridge.js";
import { generateCarRpcEngine } from "../generators/car-rpc-engine.js";
import type { AnalysisData } from "../types.js";
import { readState, writeState, createInitialState, updateStep } from "../state/manager.js";

interface Selection { readonly selected: readonly string[]; }

function readSelection(path: string): Selection | null {
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return null;
  }
}

function writeProtected(filePath: string, content: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  try {
    writeFileSync(filePath, content, { encoding: "utf-8", flag: "wx" });
  } catch {
    // File already exists — skip silently
  }
}

function writeGenerated(filePath: string, content: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (existsSync(filePath)) process.stderr.write(`[scaffold] overwriting generated file: ${filePath}\n`);
  writeFileSync(filePath, content, { encoding: "utf-8" });
}

function generatePackageJson(analysis: AnalysisData, frameworkRelPath: string): string {
  const appName = analysis.app.name;
  return JSON.stringify({
    name: `@im/mcp-${appName}`,
    version: "0.1.0",
    description: `MCP Server for ${appName}`,
    type: "module",
    main: "dist/index.js",
    scripts: {
      build: "tsc",
      start: "node dist/index.js",
      test: "vitest run",
      "test:watch": "vitest",
    },
    dependencies: {
      "@im/mcp-server-framework": `file:${frameworkRelPath}`,
      "@modelcontextprotocol/sdk": "^1.12.0",
      zod: "^3.24.0",
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      typescript: "^5.7.0",
      vitest: "^3.0.0",
    },
  }, null, 2) + "\n";
}

function generateTsconfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: "ES2022",
      module: "Node16",
      moduleResolution: "Node16",
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: true,
      sourceMap: true,
    },
    include: ["src/**/*.ts"],
    exclude: ["node_modules", "dist", "tests"],
  }, null, 2) + "\n";
}

function generateVitestConfig(): string {
  return `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    root: ".",
    include: ["tests/**/*.test.ts"],
    globals: false,
  },
});
`;
}

function generateShutdownTs(): string {
  return `import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

export function registerGracefulShutdown(server: McpServer): void {
  let shuttingDown = false;

  async function shutdown(signal: string): Promise<void> {
    if (shuttingDown) return;
    shuttingDown = true;
    process.stderr.write(\`[shutdown] Received \${signal}, closing server...\\n\`);
    try {
      await server.close();
    } catch (err) {
      process.stderr.write(\`[shutdown] Error closing: \${err}\\n\`);
    }
    process.exit(0);
  }

  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));
}
`;
}

function generateConfigYaml(analysis: AnalysisData): string {
  const domains = [...new Set(analysis.capabilities.map((c) => c.domain))];
  const safetyLevels = [...new Set(analysis.capabilities.map((c) => c.safetyLevel))];
  return `# MCP Server configuration for ${analysis.app.name}
# Generated by mcp-pipeline scaffold

app:
  name: "${analysis.app.name}"
  domain: "${analysis.app.domain}"
  framework: "${analysis.app.framework}"

adapter:
  mock_mode: true

adb:
  # "adb" resolves via PATH on any OS (Windows/macOS/Linux). Override to a
  # concrete path (e.g. ../../tools/adb/adb.exe) only if bundling your own adb.
  path: "adb"
  use_host: true
  timeout_ms: 10000

domains:
${domains.map((d) => `  - ${d}`).join("\n")}

safety_levels:
${safetyLevels.map((s) => `  - ${s}`).join("\n")}
`;
}

function generateIndexTs(): string {
  return `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { createServer } from "./server.js";
import { registerGracefulShutdown } from "./shutdown.js";
import { readConfig } from "./config.js";

async function main(): Promise<void> {
  const config = readConfig();
  const server = createServer(config);
  registerGracefulShutdown(server);

  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write("[mcp-server] Connected via stdio transport\\n");
}

main().catch((error) => {
  process.stderr.write(\`[mcp-server] Fatal: \${error}\\n\`);
  process.exit(1);
});
`;
}

function generateConfigTs(): string {
  return `import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

export interface AdbConfig {
  readonly path: string; // resolved absolute path
  readonly use_host: boolean;
  readonly timeout_ms: number;
}

export interface ServerConfig {
  readonly adapter: {
    readonly mock_mode: boolean;
  };
  readonly adb: AdbConfig;
}

const __dirname = dirname(fileURLToPath(import.meta.url));

const DEFAULT_ADB_PATH = "adb"; // resolves via PATH on any OS
const DEFAULT_CONFIG: ServerConfig = {
  adapter: { mock_mode: true },
  adb: { path: DEFAULT_ADB_PATH, use_host: true, timeout_ms: 10000 },
};

function parseMockMode(yaml: string): boolean {
  // Find adapter: section, then mock_mode: value
  const adapterMatch = yaml.match(/adapter:[\\s\\S]*?mock_mode:\\s*(\\w+)/);
  if (adapterMatch && adapterMatch[1]) {
    return adapterMatch[1] !== "false";
  }
  return true; // default to mock
}

function parseAdb(yaml: string): AdbConfig {
  const pathMatch = yaml.match(/adb:[\\s\\S]*?path:\\s*["']?([^"'\\n]+)["']?/);
  const hostMatch = yaml.match(/adb:[\\s\\S]*?use_host:\\s*(\\w+)/);
  const timeoutMatch = yaml.match(/adb:[\\s\\S]*?timeout_ms:\\s*(\\d+)/);
  const rawPath = pathMatch && pathMatch[1] ? pathMatch[1].trim() : DEFAULT_ADB_PATH;
  // A bare command name (e.g. "adb") resolves via PATH when spawned; keep it as-is.
  // A path with a separator (/ or \\) is resolved against conf/ dir to an absolute path.
  const looksLikeBareCommand = rawPath.indexOf("/") === -1 && rawPath.indexOf("\\\\") === -1;
  const absPath = looksLikeBareCommand ? rawPath : resolve(__dirname, "..", "conf", rawPath);
  return {
    path: absPath,
    use_host: hostMatch && hostMatch[1] ? hostMatch[1] !== "false" : true,
    timeout_ms: timeoutMatch && timeoutMatch[1] ? parseInt(timeoutMatch[1], 10) : 10000,
  };
}

export function readConfig(configPath?: string): ServerConfig {
  const path = configPath ?? resolve(__dirname, "..", "conf", "config.yaml");
  if (!existsSync(path)) return DEFAULT_CONFIG;

  try {
    const raw = readFileSync(path, "utf-8");
    return { adapter: { mock_mode: parseMockMode(raw) }, adb: parseAdb(raw) };
  } catch {
    return DEFAULT_CONFIG;
  }
}
`;
}

function generateAdapterFactory(analysis: AnalysisData): string {
  return `import type { IAdapter } from "./types.js";
import type { MockAdapterControl } from "./mock-adapter.js";
import { createMockAdapter } from "./mock-adapter.js";
import { createYunosAdapter } from "./yunos-adapter.js";
import type { ServerConfig } from "../config.js";

export type { IAdapter } from "./types.js";
export type { MockAdapterControl } from "./mock-adapter.js";
export type * from "./types.js";

export function createAdapter(config: ServerConfig): { adapter: IAdapter; control: MockAdapterControl | null } {
  if (config.adapter.mock_mode) {
    const { adapter, control } = createMockAdapter();
    return { adapter, control };
  }
  // SP-B: yunos-adapter.ts is deterministically generated by scaffold — createYunosAdapter
  // routes every capability method through rpcCall (no throw-stub). mock_mode:false controls the car.
  return { adapter: createYunosAdapter(config.adb), control: null };
}
`;
}

function generateServerTs(analysis: AnalysisData): string {
  const domains = [...new Set(analysis.capabilities.map((c) => c.domain))];
  const domainImports = domains.map((d) => `import { register${d.charAt(0).toUpperCase() + d.slice(1)}Tools } from "./tools/${d}.js";`).join("\n");

  const hasSafetySensitive = analysis.capabilities.some(
    (c) => c.safetyLevel !== "readonly" && c.safetyLevel !== "normal",
  );

  const safetySetup = hasSafetySensitive
    ? `import { createSafetyGuard, registerHealthTool } from "@im/mcp-server-framework";
import { TOOL_REGISTRY } from "./tools/registry.js";

function createSafetyBridge(adapter: import("./adapters/types.js").IAdapter) {
  const dyn = adapter as unknown as Record<string, unknown>;
  return {
    getGearStatus: () => {
      if (typeof dyn.readGearStatus === "function") {
        return (dyn.readGearStatus as () => Promise<{ isParked: boolean; ignoreMode: boolean }>)();
      }
      // fail-closed: app has no readGearStatus → can't verify Park → treat as not parked so p_gear_required tools are blocked
      return Promise.resolve({ isParked: false, ignoreMode: false });
    },
    getHotspotInfo: () => {
      if (typeof dyn.getHotspotInfo === "function") {
        return (dyn.getHotspotInfo as () => Promise<{ ssid: string | null }>)();
      }
      return Promise.resolve({ ssid: null });
    },
  };
}`
    : `import { registerHealthTool } from "@im/mcp-server-framework";`;

  return `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { createAdapter } from "./adapters/index.js";
import type { ServerConfig } from "./config.js";
${safetySetup}
${domainImports}

export function createServer(config: ServerConfig): McpServer {
  const server = new McpServer({
    name: "${analysis.app.name}",
    version: "0.1.0",
  });

  const { adapter } = createAdapter(config);
  registerHealthTool(server);
${hasSafetySensitive ? `
  const guard = createSafetyGuard(createSafetyBridge(adapter));
  const registryEntries = Object.fromEntries(
    TOOL_REGISTRY.map(e => [e.id, e.safetyLevel]),
  );
` : ""}
${domains.map((d) => `  register${d.charAt(0).toUpperCase() + d.slice(1)}Tools(server, adapter${hasSafetySensitive ? ", guard, registryEntries" : ""});`).join("\n")}

  return server;
}
`;
}

export function scaffoldProject(analysis: AnalysisData, outputDir: string, frameworkPath?: string, opts?: { selectionPath?: string }): void {
  if (opts?.selectionPath) {
    const sel = readSelection(resolve(opts.selectionPath));
    if (sel?.selected) analysis = { ...analysis, capabilities: analysis.capabilities.filter((c) => sel.selected.includes(c.id)) };
  }
  const resolvedFramework = resolve(frameworkPath ?? DEFAULT_FRAMEWORK_PATH);
  const frameworkRelPath = relative(outputDir, resolvedFramework).replace(/\\/g, "/");

  const files: Array<{ readonly path: string; readonly content: string }> = [
    { path: "package.json", content: generatePackageJson(analysis, frameworkRelPath) },
    { path: "tsconfig.json", content: generateTsconfig() },
    { path: "vitest.config.ts", content: generateVitestConfig() },
    { path: "conf/config.yaml", content: generateConfigYaml(analysis) },
    { path: "src/index.ts", content: generateIndexTs() },
    { path: "src/config.ts", content: generateConfigTs() },
    { path: "src/server.ts", content: generateServerTs(analysis) },
    { path: "src/shutdown.ts", content: generateShutdownTs() },
    { path: "src/adapters/types.ts", content: generateAdapterTypes(analysis) },
    { path: "src/adapters/mock-adapter.ts", content: generateMockAdapter(analysis) },
    { path: "src/adapters/index.ts", content: generateAdapterFactory(analysis) },
    { path: "src/types/enums.ts", content: generateEnums(analysis) },
    { path: "src/types/errors.ts", content: generateErrors(analysis) },
    { path: "src/tools/registry.ts", content: generateRegistry(analysis) },
    { path: "tests/contract/registry.test.ts", content: generateContractTests(analysis) },
    { path: "tests/unit/mock-adapter.test.ts", content: generateMockAdapterTests(analysis) },
    { path: "src/adapters/yunos-adapter.ts", content: generateYunosAdapterRpc(analysis) },
  ];

  for (const file of files) {
    const fullPath = resolve(outputDir, file.path);
    const fn = file.path === "conf/config.yaml" ? writeProtected : writeGenerated;
    fn(fullPath, file.content);
  }

  const domainFiles = generateToolHandlers(analysis);
  for (const [filePath, content] of domainFiles) {
    const fullPath = resolve(outputDir, filePath);
    writeGenerated(fullPath, content);
  }

  const rpcFiles = generateRpcBridge(analysis);
  for (const [filePath, content] of rpcFiles) {
    const fullPath = resolve(outputDir, filePath);
    writeGenerated(fullPath, content);
  }

  const carFiles = generateCarRpcEngine(analysis);
  for (const [filePath, content] of carFiles) {
    const fullPath = resolve(outputDir, filePath);
    writeGenerated(fullPath, content);
  }
}

export async function scaffoldCommand(args: string[]): Promise<void> {
  const inputPath = args.find((a) => !a.startsWith("--"));
  const outputFlag = args.indexOf("--output");
  const outputPath = outputFlag !== -1 ? args[outputFlag + 1] : null;
  const frameworkFlag = args.indexOf("--framework-path");
  const frameworkPath = frameworkFlag !== -1 ? args[frameworkFlag + 1] : undefined;

  if (!inputPath) {
    throw new Error("Usage: mcp-pipeline scaffold <analysis.json> --output <dir> [--framework-path <path>]");
  }

  let analysis: AnalysisData;
  try {
    analysis = JSON.parse(readFileSync(resolve(inputPath), "utf-8"));
  } catch (error) {
    throw new Error(`Error reading ${inputPath}: ${error instanceof Error ? error.message : String(error)}`);
  }

  const validation = validateAnalysis(analysis);
  if (!validation.valid) {
    throw new Error(`Invalid analysis.json:
${validation.errors.map((e) => `  ${e.path}: ${e.message}`).join("\n")}`);
  }

  const appName = analysis.app?.name ?? "unknown";
  const outDir = outputPath ?? `./mcp-${appName}`;

  let state = readState(appName) ?? createInitialState(appName, resolve(outDir));
  try {
    state = updateStep(state, "scaffold", { status: "in_progress" });
    writeState(state);
  } catch {}

  try {
    scaffoldProject(analysis, resolve(outDir), frameworkPath);
    try {
      state = updateStep(state, "scaffold", { status: "completed" });
      writeState(state);
    } catch {}
    process.stdout.write(`Scaffolded: ${resolve(outDir)}
`);
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    try {
      state = updateStep(state, "scaffold", { status: "failed", error: errorMsg });
      writeState(state);
    } catch {}
    throw error;
  }
}
