import { mkdirSync, writeFileSync, existsSync, readFileSync } from "fs";
import { resolve, dirname, relative, basename } from "path";
import { fileURLToPath } from "url";

// Framework lives at <monorepo>/framework, a sibling of cli/. Resolving from
// this module's own location (cli/src/commands/scaffold.ts) is CWD-independent
// and matches the semantics the e2e tests pass via FRAMEWORK_DIR.
const DEFAULT_FRAMEWORK_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "framework");
import { validateAnalysis } from "./validate.js";
import { generateEnums } from "../generators/enums.js";
import { generateErrors } from "../generators/errors.js";
import { generateRegistry } from "../generators/registry.js";
import { generateContractTests } from "../generators/contract-tests.js";
import { generateToolSchema } from "../generators/tool-schema.js";
import { generateRpcBridge } from "../generators/rpc-bridge.js";
import { generateCarRpcEngine } from "../generators/car-rpc-engine.js";
import { generateAidlRegistry } from "../generators/aidl-registry.js";
import type { AnalysisData } from "../types.js";
import { readState, writeState, createInitialState, updateStep } from "../state/manager.js";

interface Selection { readonly selected: readonly string[]; }

function readSelection(path: string): Selection | null {
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return null;
  }
}

function writeProtected(filePath: string, content: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  try {
    writeFileSync(filePath, content, { encoding: "utf-8", flag: "wx" });
  } catch {
    // File already exists — skip silently
  }
}

function writeGenerated(filePath: string, content: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (existsSync(filePath)) process.stderr.write(`[scaffold] overwriting generated file: ${filePath}\n`);
  writeFileSync(filePath, content, { encoding: "utf-8" });
}

function generatePackageJson(analysis: AnalysisData, frameworkRelPath: string): string {
  const appName = analysis.app.name;
  return JSON.stringify({
    name: `@im/mcp-${appName}`,
    version: "0.1.0",
    description: `MCP Server for ${appName}`,
    type: "module",
    main: "dist/index.js",
    scripts: {
      build: "tsc",
      start: "node dist/index.js",
      test: "vitest run",
      "test:watch": "vitest",
    },
    dependencies: {
      "@im/mcp-server-framework": `file:${frameworkRelPath}`,
      "@modelcontextprotocol/sdk": "^1.12.0",
      zod: "^3.24.0",
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      typescript: "^5.7.0",
      vitest: "^3.0.0",
    },
  }, null, 2) + "\n";
}

function generateTsconfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: "ES2022",
      module: "Node16",
      moduleResolution: "Node16",
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: true,
      sourceMap: true,
    },
    include: ["src/**/*.ts"],
    exclude: ["node_modules", "dist", "tests"],
  }, null, 2) + "\n";
}

function generateVitestConfig(): string {
  return `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    root: ".",
    include: ["tests/**/*.test.ts"],
    globals: false,
  },
});
`;
}

function generateShutdownTs(): string {
  return `import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

export function registerGracefulShutdown(server: McpServer): void {
  let shuttingDown = false;

  async function shutdown(signal: string): Promise<void> {
    if (shuttingDown) return;
    shuttingDown = true;
    process.stderr.write(\`[shutdown] Received \${signal}, closing server...\\n\`);
    try {
      await server.close();
    } catch (err) {
      process.stderr.write(\`[shutdown] Error closing: \${err}\\n\`);
    }
    process.exit(0);
  }

  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));
}
`;
}

function generateConfigYaml(analysis: AnalysisData): string {
  const domains = [...new Set(analysis.capabilities.map((c) => c.domain))];
  const safetyLevels = [...new Set(analysis.capabilities.map((c) => c.safetyLevel))];
  return `# MCP Server configuration for ${analysis.app.name}
# Generated by mcp-pipeline scaffold

app:
  name: "${analysis.app.name}"
  domain: "${analysis.app.domain}"
  framework: "${analysis.app.framework}"

adapter:
  mock_mode: true

adb:
  # "adb" resolves via PATH on any OS (Windows/macOS/Linux). Override to a
  # concrete path (e.g. ../../tools/adb/adb.exe) only if bundling your own adb.
  path: "adb"
  use_host: true
  timeout_ms: 10000

domains:
${domains.map((d) => `  - ${d}`).join("\n")}

safety_levels:
${safetyLevels.map((s) => `  - ${s}`).join("\n")}
`;
}

function generateIndexTs(): string {
  return `import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { createServer } from "./server.js";
import { readConfig } from "./config.js";

async function main(): Promise<void> {
  const config = readConfig();
  const server = createServer(config);
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write("[mcp-server] Connected via stdio transport\\n");

  const shutdown = async (): Promise<void> => {
    try { await server.close(); } catch { /* ignore close errors on shutdown */ }
    process.exit(0);
  };
  process.on("SIGINT", () => void shutdown());
  process.on("SIGTERM", () => void shutdown());
}

main().catch((error) => {
  process.stderr.write(\`[mcp-server] Fatal: \${error}\\n\`);
  process.exit(1);
});
`;
}

function generateConfigTs(): string {
  return `import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

export interface AdbConfig {
  readonly path: string; // resolved absolute path
  readonly use_host: boolean;
  readonly timeout_ms: number;
}

export interface ServerConfig {
  readonly adapter: {
    readonly mock_mode: boolean;
  };
  readonly adb: AdbConfig;
}

const __dirname = dirname(fileURLToPath(import.meta.url));

const DEFAULT_ADB_PATH = "adb"; // resolves via PATH on any OS
const DEFAULT_CONFIG: ServerConfig = {
  adapter: { mock_mode: true },
  adb: { path: DEFAULT_ADB_PATH, use_host: true, timeout_ms: 10000 },
};

function parseMockMode(yaml: string): boolean {
  // Find adapter: section, then mock_mode: value
  const adapterMatch = yaml.match(/adapter:[\\s\\S]*?mock_mode:\\s*(\\w+)/);
  if (adapterMatch && adapterMatch[1]) {
    return adapterMatch[1] !== "false";
  }
  return true; // default to mock
}

function parseAdb(yaml: string): AdbConfig {
  const pathMatch = yaml.match(/adb:[\\s\\S]*?path:\\s*["']?([^"'\\n]+)["']?/);
  const hostMatch = yaml.match(/adb:[\\s\\S]*?use_host:\\s*(\\w+)/);
  const timeoutMatch = yaml.match(/adb:[\\s\\S]*?timeout_ms:\\s*(\\d+)/);
  const rawPath = pathMatch && pathMatch[1] ? pathMatch[1].trim() : DEFAULT_ADB_PATH;
  // A bare command name (e.g. "adb") resolves via PATH when spawned; keep it as-is.
  // A path with a separator (/ or \\) is resolved against conf/ dir to an absolute path.
  const looksLikeBareCommand = rawPath.indexOf("/") === -1 && rawPath.indexOf("\\\\") === -1;
  const absPath = looksLikeBareCommand ? rawPath : resolve(__dirname, "..", "conf", rawPath);
  return {
    path: absPath,
    use_host: hostMatch && hostMatch[1] ? hostMatch[1] !== "false" : true,
    timeout_ms: timeoutMatch && timeoutMatch[1] ? parseInt(timeoutMatch[1], 10) : 10000,
  };
}

export function readConfig(configPath?: string): ServerConfig {
  const path = configPath ?? resolve(__dirname, "..", "conf", "config.yaml");
  if (!existsSync(path)) return DEFAULT_CONFIG;

  try {
    const raw = readFileSync(path, "utf-8");
    return { adapter: { mock_mode: parseMockMode(raw) }, adb: parseAdb(raw) };
  } catch {
    return DEFAULT_CONFIG;
  }
}
`;
}

function generateAdapterFactory(analysis: AnalysisData): string {
  const gearId = analysis.app.safetyProbes?.gear;
  const hotspotId = analysis.app.safetyProbes?.hotspot;
  const probeMocks: string[] = [];
  if (gearId) probeMocks.push(`      if (op === ${JSON.stringify(gearId)}) return { isParked: true, ignoreMode: false };`);
  if (hotspotId) probeMocks.push(`      if (op === ${JSON.stringify(hotspotId)}) return { ssid: "mock-hotspot" };`);
  const probeBlock = probeMocks.length > 0
    ? probeMocks.join("\n") + "\n"
    : "      // no safetyProbes declared — no probe mocks injected\n";
  return `import { rpcCall as realRpcCall } from "../rpc/rpc-client.js";
import type { ServerConfig } from "../config.js";

/** Schema-first adapter.
 *  Function schemas are generated directly from analysis for the upstream agent;
 *  runtime dispatch maps tool op -> real wire through rpcCall(op, args). */
export interface Adapter {
  rpcCall(op: string, args: Record<string, unknown>): Promise<unknown>;
}

export function createAdapter(config: ServerConfig): { adapter: Adapter } {
  if (config.adapter.mock_mode) {
    // mock: placeholders so the server runs end-to-end with no device. Only the app's DECLARED
    // safety probes (analysis.app.safetyProbes) get shaped returns; all other ops: a success stub.
    return { adapter: { rpcCall: async (op: string) => {
${probeBlock}      return { success: true };
    } } };
  }
  const adb = config.adb;
  return { adapter: { rpcCall: (op, args) => realRpcCall(op, args, adb) } };
}
`;
}

function generateServerTs(analysis: AnalysisData): string {
  const hasSafety = analysis.capabilities.some((c) => c.safetyLevel !== "readonly" && c.safetyLevel !== "normal");
  const safetyImport = hasSafety
    ? `import { createSafetyGuard, resolveSafetyRules, formatSuccess, formatError } from "@im/mcp-server-framework";`
    : `import { formatSuccess, formatError } from "@im/mcp-server-framework";`;
  // Gear/hotspot probe capability ids are DECLARED in analysis.app.safetyProbes (no hardcoded ids,
  // no keyword heuristic). A missing probe means the guard cannot verify that precondition → the
  // corresponding p_gear_* tools fail-closed (rejected) rather than silently passing.
  const gearId = analysis.app.safetyProbes?.gear;
  const hotspotId = analysis.app.safetyProbes?.hotspot;
  const gearFn = gearId
    ? `try { return (await rpcCall(${JSON.stringify(gearId)}, {})) as { isParked: boolean; ignoreMode: boolean }; } catch { return { isParked: false, ignoreMode: false }; }`
    : `return { isParked: false, ignoreMode: false }; /* no gear probe declared → fail-closed */`;
  const hotspotFn = hotspotId
    ? `try { return (await rpcCall(${JSON.stringify(hotspotId)}, {})) as { ssid: string | null }; } catch { return { ssid: null }; }`
    : `return { ssid: null }; /* no hotspot probe declared → fail-closed */`;
  const safetyBlock = hasSafety ? `
  // Safety bridge: read gear/hotspot via rpcCall to the app's DECLARED probe capability
  // (analysis.app.safetyProbes). Undeclared probes fail-closed — the guard rejects rather than
  // guesses. Per-app, never hardcoded ids.
  const guard = createSafetyGuard({
    getGearStatus: async () => { ${gearFn} },
    getHotspotInfo: async () => { ${hotspotFn} },
  }, resolveSafetyRules(${JSON.stringify(analysis.app.safetyRules ?? {})}));
  const safetyByTool = new Map(TOOL_REGISTRY.map((e) => [e.id, e.safetyLevel] as const));` : "";
  const guardCall = hasSafety ? `
    const level = safetyByTool.get(name);
    if (level) {
      try { await guard(level, (args ?? {}) as Record<string, unknown>); }
      catch (e) { return formatError((e as { code?: number }).code ?? 1000, (e as Error).message ?? String(e), "safety"); }
    }` : "";

  return `import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { ListToolsRequestSchema, CallToolRequestSchema } from "@modelcontextprotocol/sdk/types.js";
${safetyImport}
import { createAdapter } from "./adapters/index.js";
import { TOOL_SCHEMA } from "./tools/schema.js";
import { TOOL_REGISTRY } from "./tools/registry.js";
import type { ServerConfig } from "./config.js";
import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Read rpc/config.json _deferred at request time — always reflects the current wire set. */
function readDeferred(): Set<string> {
  const p = resolve(__dirname, "..", "rpc", "config.json");
  if (!existsSync(p)) return new Set();
  try {
    const cfg = JSON.parse(readFileSync(p, "utf-8"));
    const def = cfg?._deferred;
    if (def && typeof def === "object" && !Array.isArray(def)) return new Set(Object.keys(def as Record<string, unknown>));
  } catch { /* malformed config — treat as no deferred */ }
  return new Set();
}

const HEALTH_TOOL = { name: "health_check", description: "Liveness probe — returns {status:'ok'}.", inputSchema: { type: "object", properties: {} } };

export function createServer(config: ServerConfig): Server {
  const server = new Server({ name: "${analysis.app.name}", version: "0.1.0" }, { capabilities: { tools: {} } });
  const { adapter: { rpcCall } } = createAdapter(config);
${safetyBlock}

  server.setRequestHandler(ListToolsRequestSchema, async () => {
    const deferred = readDeferred();
    return {
      // Deferred tools (no wire in rpc/config.json) are hidden from tools/list — a weak agent can't call
      // (and waste a turn 4004-ing) what it can't see. CallTool still 4004s as defense-in-depth.
      tools: [HEALTH_TOOL, ...TOOL_SCHEMA.filter((t) => !deferred.has(t.name)).map((t) => ({ name: t.name, description: t.description, inputSchema: t.inputSchema, ...(t.outputSchema ? { outputSchema: t.outputSchema } : {}), annotations: t.annotations }))],
    };
  });

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args } = request.params;
    if (name === "health_check") return formatSuccess({ status: "ok" });
    if (readDeferred().has(name)) return formatError(4004, "tool '" + name + "' is deferred (no wire in rpc/config.json)", "general");
    if (!TOOL_REGISTRY.some((e) => e.id === name)) return formatError(4004, "unknown tool: " + name, "general");
${guardCall}
    try {
      return formatSuccess(await rpcCall(name, (args ?? {}) as Record<string, unknown>));
    } catch (e) {
      return formatError((e as { code?: number }).code ?? 1000, (e as Error).message ?? String(e), "rpc");
    }
  });

  return server;
}
`;
}

export function scaffoldProject(analysis: AnalysisData, outputDir: string, frameworkPath?: string, opts?: { selectionPath?: string }): void {
  if (opts?.selectionPath) {
    const selPath = resolve(opts.selectionPath);
    const sel = readSelection(selPath);
    if (!sel || !Array.isArray(sel.selected)) {
      throw new Error(`selection.json missing or invalid (expected { "selected": [...] }): ${selPath}`);
    }
    if (sel.selected.length === 0) {
      throw new Error(`selection.json has an empty "selected" list — nothing to generate: ${selPath}`);
    }
    const missing = sel.selected.filter((id) => !analysis.capabilities.some((c) => c.id === id));
    if (missing.length > 0) {
      throw new Error(`selection.json references unknown capability ids (not in analysis): ${missing.join(", ")}`);
    }
    analysis = { ...analysis, capabilities: analysis.capabilities.filter((c) => sel.selected.includes(c.id)) };
  }
  const resolvedFramework = resolve(frameworkPath ?? DEFAULT_FRAMEWORK_PATH);
  const frameworkRelPath = relative(outputDir, resolvedFramework).replace(/\\/g, "/");

  const files: Array<{ readonly path: string; readonly content: string }> = [
    { path: "package.json", content: generatePackageJson(analysis, frameworkRelPath) },
    { path: "tsconfig.json", content: generateTsconfig() },
    { path: "vitest.config.ts", content: generateVitestConfig() },
    { path: "conf/config.yaml", content: generateConfigYaml(analysis) },
    { path: "src/index.ts", content: generateIndexTs() },
    { path: "src/config.ts", content: generateConfigTs() },
    { path: "src/server.ts", content: generateServerTs(analysis) },
    { path: "src/adapters/index.ts", content: generateAdapterFactory(analysis) },
    { path: "src/types/enums.ts", content: generateEnums(analysis) },
    { path: "src/types/errors.ts", content: generateErrors(analysis) },
    { path: "src/tools/registry.ts", content: generateRegistry(analysis) },
    { path: "src/tools/schema.ts", content: generateToolSchema(analysis) },
    { path: "tests/contract/registry.test.ts", content: generateContractTests(analysis) },
  ];

  for (const file of files) {
    const fullPath = resolve(outputDir, file.path);
    const fn = file.path === "conf/config.yaml" ? writeProtected : writeGenerated;
    fn(fullPath, file.content);
  }

  const rpcFiles = generateRpcBridge(analysis);
  for (const [filePath, content] of rpcFiles) {
    const fullPath = resolve(outputDir, filePath);
    writeGenerated(fullPath, content);
  }

  // Substrate branch on app.framework. android-kotlin: the car-side artifact is the AIDL dispatch
  // registry (consumed by the Kotlin executor in Plan B); the agil RpcEngine page is irrelevant, so
  // skip it. rpc-bridge (host rpc-client) still emits — the host TS server imports it; mock_mode keeps
  // the project runnable, and the real android-aidl rpc (am startservice trigger) lands in Plan B.
  if (analysis.app.framework === "android-kotlin") {
    writeGenerated(resolve(outputDir, "car-side/registry.json"), generateAidlRegistry(analysis));
  } else {
    const carFiles = generateCarRpcEngine(analysis);
    for (const [filePath, content] of carFiles) {
      const fullPath = resolve(outputDir, filePath);
      writeGenerated(fullPath, content);
    }
  }
}

export async function scaffoldCommand(args: string[]): Promise<void> {
  const inputPath = args.find((a) => !a.startsWith("--"));
  const outputFlag = args.indexOf("--output");
  const outputPath = outputFlag !== -1 ? args[outputFlag + 1] : null;
  const frameworkFlag = args.indexOf("--framework-path");
  const frameworkPath = frameworkFlag !== -1 ? args[frameworkFlag + 1] : undefined;
  const selectionFlag = args.indexOf("--selection");
  const selectionPath = selectionFlag !== -1 ? args[selectionFlag + 1] : undefined;

  if (!inputPath) {
    throw new Error("Usage: mcp-pipeline scaffold <analysis.json> --output <dir> [--framework-path <path>] --selection <selection.json>");
  }

  // curate is mandatory — scaffold refuses to run without an explicit selection.json (produced by
  // `mcp-pipeline curate`). This is the hard enforcement that makes curate un-skippable: every
  // capability set that becomes MCP tools must be an explicit user choice, never a silent default.
  if (!selectionPath) {
    throw new Error(
      "curate is mandatory: --selection <selection.json> is required.\n" +
      "Run `mcp-pipeline curate <analysis.json>` first to choose which capabilities become MCP tools\n" +
      "(interactive selector in a terminal, or `--selected <ids>` / `--all` for non-interactive use),\n" +
      "then re-run scaffold with --selection <selection.json>. curate cannot be skipped."
    );
  }

  let analysis: AnalysisData;
  try {
    analysis = JSON.parse(readFileSync(resolve(inputPath), "utf-8"));
  } catch (error) {
    throw new Error(`Error reading ${inputPath}: ${error instanceof Error ? error.message : String(error)}`);
  }

  const validation = validateAnalysis(analysis);
  if (!validation.valid) {
    throw new Error(`Invalid analysis.json:
${validation.errors.map((e) => `  ${e.path}: ${e.message}`).join("\n")}`);
  }

  const appName = analysis.app?.name ?? "unknown";
  const outDir = outputPath ?? `./mcp-${appName}`;

  let state = readState(appName) ?? createInitialState(appName, resolve(outDir));
  try {
    state = updateStep(state, "scaffold", { status: "in_progress" });
    writeState(state);
  } catch {}

  try {
    scaffoldProject(analysis, resolve(outDir), frameworkPath, selectionPath ? { selectionPath: resolve(selectionPath) } : undefined);
    try {
      state = updateStep(state, "scaffold", { status: "completed" });
      writeState(state);
    } catch {}
    process.stdout.write(`Scaffolded: ${resolve(outDir)}
`);
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    try {
      state = updateStep(state, "scaffold", { status: "failed", error: errorMsg });
      writeState(state);
    } catch {}
    throw error;
  }
}
